import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { validateConfig } from '../src/config/schema';
import { translatronxConfig } from '../src/config/schema';

describe('Configuration Property Tests', () => {
    it('should validate valid configurations generated by fast-check', () => {
        // Define a generator for a valid configuration
        const configArb = fc.record({
            sourceLanguage: fc.constantFrom('en', 'es', 'fr', 'de', 'ja', 'zh'),
            targetLanguages: fc.array(fc.record({
                language: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-zA-Z]/g, 'x')),
                shortCode: fc.string({ minLength: 2, maxLength: 5 }).map(s => s.toLowerCase().replace(/[^a-z]/g, 'x')),
            }), { minLength: 1, maxLength: 3 }),
            extractors: fc.array(fc.record({
                type: fc.constant('json'),
                pattern: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-z0-9]/g, 'x') + '.json'),
            }), { minLength: 1, maxLength: 2 }),
            providers: fc.array(fc.record({
                name: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-z]/g, 'x')),
                type: fc.constant('openai'),
                model: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-z0-9-]/g, 'x')),
                apiKey: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-zA-Z0-9]/g, 'x')),
                temperature: fc.float({ min: 0, max: 1, noNaN: true }),
                maxRetries: fc.integer({ min: 0, max: 10 }),
            }), { minLength: 1, maxLength: 2 }),
            validation: fc.record({
                preservePlaceholders: fc.boolean(),
                maxLengthRatio: fc.integer({ min: 1, max: 10 }),
                preventSourceLeakage: fc.boolean(),
            }),
            output: fc.record({
                dir: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-z]/g, 'x')),
                format: fc.constant('json'),
                flat: fc.boolean(),
                indent: fc.integer({ min: 0, max: 4 }),
            }),
            advanced: fc.record({
                batchSize: fc.integer({ min: 1, max: 100 }),
                concurrency: fc.integer({ min: 1, max: 10 }),
                cacheDir: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-z]/g, 'x')),
                ledgerPath: fc.string({ minLength: 1 }).map(s => s.replace(/[^a-z]/g, 'x') + '.sqlite'),
                verbose: fc.boolean(),
            }),
        });

        fc.assert(
            fc.property(configArb, (config) => {
                const result = validateConfig(config as any);
                expect(result).toBeDefined();
            })
        );
    });
});
