import { readFileSync } from 'node:fs';
import type { SourceUnit } from '../core/domain.js';

/** Apply the context metadata generated by `translatronx context generate`. */
export function applySourceContext(units: SourceUnit[], filePath: string, keyPrefix?: string): void {
    let data: unknown;
    try {
        data = JSON.parse(readFileSync(filePath, 'utf-8'));
    } catch (error) {
        throw new Error(`Cannot read context file ${filePath}: ${error instanceof Error ? error.message : String(error)}`);
    }

    const contextByKey = new Map<string, string>();
    function collect(node: unknown, path: string[]): void {
        if (node === null || typeof node !== 'object' || Array.isArray(node)) return;
        const record = node as Record<string, unknown>;
        if (typeof record.value === 'string') {
            if (typeof record.context === 'string' && record.context.trim() !== '') {
                contextByKey.set(path.join('.'), record.context);
            }
            return;
        }
        for (const [key, value] of Object.entries(record)) collect(value, [...path, key]);
    }
    collect(data, []);

    for (const unit of units) {
        const key = keyPrefix && unit.keyPath.startsWith(`${keyPrefix}.`)
            ? unit.keyPath.slice(keyPrefix.length + 1)
            : unit.keyPath;
        const context = contextByKey.get(key);
        if (context !== undefined) unit.context = context;
    }
}
